require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 200

Rails/I18nLocaleTexts:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments





