require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 200

Rails/I18nLocaleTexts:
  Enabled: false

# Rails/FilePath:
#   EnforcedStyle: arguments

convention:Metrics/BlockLength:
  Max: 70

RSpec/MultipleExpectations:
  Max: 100

RSpec/ExampleLength:
  Max: 100

RSpec/FilePath:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false



